---
-   name: Provision Site
    hosts: all
    remote_user: root
    vars:
        certbot_email: mail@my-auction.pro
        certbot_hosts:
            - demo-auction.my-auction.pro
            - api.demo-auction.my-auction.pro
    tasks:
        -   import_tasks: tasks/setup_docker.yml
        -   import_tasks: tasks/setup_certbot.yml
        -   import_tasks: tasks/generate_certificates.yml
        -   import_tasks: tasks/create_user.yml

    handlers:
        -   name: Start docker on boot
            systemd:
                name: docker
                state: started
                enabled: yes
